/**
 * Aqua Lux Aruba service catalog, imported from the Concierge Info Sheet.
 * Auto-seeds the Services book on first boot after a schema upgrade (see
 * src/server.js) — only when the services table is empty, so re-deploys
 * never duplicate or overwrite services you have since edited by hand.
 */
export const SERVICE_CATALOG = [
  {
    "category": "Water Activity",
    "wix_form_name": "Jolly Pirates",
    "service_name": "Pirates Sail Boat Tour",
    "company": "Jolly Pirates",
    "contact": "",
    "booking_method": "Fare Harbour",
    "info_needed": "Tour, Date, People",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Morning Tour",
        "price": 99.0,
        "price_unit": "per_person",
        "child_price": 70.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm",
        "notes": "Swim, snorkel, rope swing aboard the pirate ship"
      },
      {
        "option_name": "Afternoon Tour",
        "price": 79.0,
        "price_unit": "per_person",
        "child_price": 56.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "2:00pm \u2013 5:00pm",
        "notes": ""
      },
      {
        "option_name": "Sunset Tour",
        "price": 66.0,
        "price_unit": "per_person",
        "child_price": 51.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "5:30pm \u2013 7:30pm",
        "notes": ""
      }
    ]
  },
  {
    "category": "Water Activity",
    "wix_form_name": "Catamaran Tour",
    "service_name": "Catamaran Tour",
    "company": "Pelican Adventures",
    "contact": "5942716 | info@pelican-aruba.com",
    "booking_method": "Ticket book + WhatsApp",
    "info_needed": "Tour, Date, People",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Brunch Tour",
        "price": 92.0,
        "price_unit": "per_person",
        "child_price": 72.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 20.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm",
        "notes": ""
      },
      {
        "option_name": "Afternoon Tour",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 50.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 20.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "2:00pm \u2013 4:30pm",
        "notes": ""
      },
      {
        "option_name": "Sunset Tour",
        "price": 79.0,
        "price_unit": "per_person",
        "child_price": 59.0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 20.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "5:30pm \u2013 7:30pm",
        "notes": ""
      }
    ]
  },
  {
    "category": "Water Activity",
    "wix_form_name": "Private Boat",
    "service_name": "Private Boat Charter",
    "company": "Around Aruba Tours",
    "contact": "5942716 | info@pelican-aruba.com",
    "booking_method": "Ticket book + WhatsApp",
    "info_needed": "Tour, Date, Timing",
    "internal_notes": "Contact copied from old sheet \u2014 same as Pelican; double-check",
    "options": [
      {
        "option_name": "10-seater",
        "price": 200.0,
        "price_unit": "per_hour",
        "child_price": 0,
        "min_people": 1,
        "max_people": 10,
        "downpayment_percent": 15.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "3\u20138 hours; latest finish 7pm",
        "notes": "Starts at Moomba"
      },
      {
        "option_name": "15-seater",
        "price": 300.0,
        "price_unit": "per_hour",
        "child_price": 0,
        "min_people": 1,
        "max_people": 15,
        "downpayment_percent": 15.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "3\u20138 hours; latest finish 7pm",
        "notes": "Starts at Moomba"
      }
    ]
  },
  {
    "category": "Water Activity",
    "wix_form_name": "AWA Aruba",
    "service_name": "Private Sailing Charter",
    "company": "AWA Aruba",
    "contact": "5621602 | booking@awaaruba.com",
    "booking_method": "WhatsApp",
    "info_needed": "Tour, Date, Timing, People",
    "internal_notes": "Includes private chef, premium liquor, 4 underwater scooters; begins in Varadero",
    "options": [
      {
        "option_name": "Half Day \u2014 base (up to 6 people)",
        "price": 2000.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": 6,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "10:30 AM \u2013 2:30 PM",
        "notes": "Private chef, premium liquor, 4 underwater scooters; begins in Varadero"
      },
      {
        "option_name": "Half Day \u2014 each additional person (7\u201315)",
        "price": 50.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 7,
        "max_people": 15,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Full Day \u2014 base (up to 6 people)",
        "price": 3000.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": 6,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "10:30 AM \u2013 6:30 PM or 11:30 AM \u2013 7:30 PM",
        "notes": ""
      },
      {
        "option_name": "Full Day \u2014 each additional person (7\u201315)",
        "price": 50.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 7,
        "max_people": 15,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Sunset \u2014 base (up to 6 people)",
        "price": 2000.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": 6,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "3:30 PM \u2013 7:30 PM",
        "notes": ""
      },
      {
        "option_name": "Sunset \u2014 each additional person (7\u201315)",
        "price": 50.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 7,
        "max_people": 15,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      }
    ]
  },
  {
    "category": "Water Activity",
    "wix_form_name": "Clear Kayak",
    "service_name": "Clear Kayak Drone Shoot",
    "company": "Island Cabana",
    "contact": "6626285 | Ethan Nagtegaal",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Clear Kayak Drone Shoot",
        "price": 65.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "30 mins",
        "notes": "Professional drone photos"
      }
    ]
  },
  {
    "category": "Water Activity",
    "wix_form_name": "Parasailing & Tubing",
    "service_name": "Water Sports",
    "company": "",
    "contact": "5631793 | Benji",
    "booking_method": "WhatsApp",
    "info_needed": "Amount of people, jetskis",
    "internal_notes": "Parasailing hourly from 10am; jet ski every half hour from 10:30 | Vendor company name not on file yet \u2014 ask & fill in.",
    "options": [
      {
        "option_name": "Parasailing",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": true,
        "timing": "10\u201312 minutes in the air; hourly from 10am",
        "notes": "\u26a0 CONFIRM: is $70 per person, and is the $20 downpayment per person? (Yes)"
      },
      {
        "option_name": "Tubing",
        "price": 25.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "15\u201320 minutes",
        "notes": "\u26a0 Yes per person"
      },
      {
        "option_name": "Jet Ski",
        "price": 85.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "30 minutes; every half hour from 10:30",
        "notes": "\u26a0 CONFIRM: is $85 per rider or per jet ski (2 riders)? Price is per jetski ride"
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "UTV Tours & Rentals",
    "service_name": "UTV Guided Tour",
    "company": "Around Aruba Tours",
    "contact": "5926644 / 7349001 | sales@aroundarubatours.com",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing, Seater",
    "internal_notes": "",
    "options": [
      {
        "option_name": "2-seater",
        "price": 190.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": "Guided tour of Aruba's outback"
      },
      {
        "option_name": "3-seater",
        "price": 285.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 3,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": ""
      },
      {
        "option_name": "4-seater",
        "price": 380.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 4,
        "downpayment_percent": 0,
        "downpayment_fixed": 40.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": ""
      },
      {
        "option_name": "5-seater",
        "price": 475.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 5,
        "downpayment_percent": 0,
        "downpayment_fixed": 40.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": ""
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "UTV Tours & Rentals",
    "service_name": "UTV Rental (self-drive)",
    "company": "Around Aruba Tours",
    "contact": "5926644 / 7349001 | sales@aroundarubatours.com",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing, Seater",
    "internal_notes": "",
    "options": [
      {
        "option_name": "2-seater \u2014 4 hours",
        "price": 230.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "4 hours",
        "notes": ""
      },
      {
        "option_name": "2-seater \u2014 8 hours",
        "price": 270.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "8 hours",
        "notes": ""
      },
      {
        "option_name": "3/4/5-seater \u2014 4 hours",
        "price": 280.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 5,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "4 hours",
        "notes": ""
      },
      {
        "option_name": "3/4/5-seater \u2014 8 hours",
        "price": 340.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 5,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "8 hours",
        "notes": ""
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "ATV Tour & Rentals",
    "service_name": "ATV Guided Tour",
    "company": "Around Aruba Tours",
    "contact": "5926644 / 7349001 | sales@aroundarubatours.com",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing, Seater",
    "internal_notes": "",
    "options": [
      {
        "option_name": "1-seater",
        "price": 130.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 1,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": ""
      },
      {
        "option_name": "2-seater",
        "price": 170.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "9:00am \u2013 1:00pm or 2:30pm \u2013 6:30pm",
        "notes": ""
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "ATV Tour & Rentals",
    "service_name": "ATV Rental (self-drive)",
    "company": "Around Aruba Tours",
    "contact": "5926644 / 7349001 | sales@aroundarubatours.com",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing, Seater",
    "internal_notes": "",
    "options": [
      {
        "option_name": "1-seater \u2014 4 hours",
        "price": 130.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 1,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "4 hours",
        "notes": ""
      },
      {
        "option_name": "1-seater \u2014 8 hours",
        "price": 160.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 1,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "8 hours",
        "notes": ""
      },
      {
        "option_name": "2-seater \u2014 4 hours",
        "price": 150.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "4 hours",
        "notes": ""
      },
      {
        "option_name": "2-seater \u2014 8 hours",
        "price": 180.0,
        "price_unit": "per_vehicle",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 0,
        "downpayment_fixed": 30.0,
        "downpayment_per_person": false,
        "timing": "8 hours",
        "notes": ""
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "Private Jeep Tour",
    "service_name": "Private Jeep Tour",
    "company": "Quinten",
    "contact": "Quinten",
    "booking_method": "WhatsApp",
    "info_needed": "People, Date",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Jeep Tour",
        "price": 100.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": true,
        "timing": "9:00am \u2013 1:00pm",
        "notes": "Natural pool, caves, coastline"
      }
    ]
  },
  {
    "category": "Adventure",
    "wix_form_name": "Open-Air Safari",
    "service_name": "Open-Air Safari",
    "company": "Around Aruba Tours",
    "contact": "5926644 / 7349001 | sales@aroundarubatours.com",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Hours, Seater, start time",
    "internal_notes": "Between 6am \u2013 6pm; customizable route",
    "options": [
      {
        "option_name": "6-seater",
        "price": 110.0,
        "price_unit": "per_hour",
        "child_price": 0,
        "min_people": 1,
        "max_people": 6,
        "downpayment_percent": 0,
        "downpayment_fixed": 40.0,
        "downpayment_per_person": false,
        "timing": "Min 3 \u2013 max 8 hours, between 6am \u2013 6pm",
        "notes": "Customizable route \u26a0 ANSWER: sheet says $60/h after 4 hours \u2014 does that apply to ALL hours or only hours 5+? (only after 4 hours"
      },
      {
        "option_name": "9-seater",
        "price": 130.0,
        "price_unit": "per_hour",
        "child_price": 0,
        "min_people": 1,
        "max_people": 9,
        "downpayment_percent": 0,
        "downpayment_fixed": 40.0,
        "downpayment_per_person": false,
        "timing": "Min 3 \u2013 max 8 hours, between 6am \u2013 6pm",
        "notes": "\u26a0 ANSWER: same two questions as the 6-seater ($70/h after 4 hours; downpayment?)"
      }
    ]
  },
  {
    "category": "Relaxation",
    "wix_form_name": "Private Massage",
    "service_name": "Private In-Villa Massage",
    "company": "My Lovely Body",
    "contact": "7488240",
    "booking_method": "WhatsApp",
    "info_needed": "People, location, time, service",
    "internal_notes": "They come to you",
    "options": [
      {
        "option_name": "Swedish \u2014 60 minutes",
        "price": 120.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "60 minutes",
        "notes": "Therapists come to you"
      },
      {
        "option_name": "Swedish \u2014 90 minutes",
        "price": 155.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "90 minutes",
        "notes": ""
      },
      {
        "option_name": "Hot Stone \u2014 60 minutes",
        "price": 135.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "60 minutes",
        "notes": ""
      },
      {
        "option_name": "Hot Stone \u2014 90 minutes (?)",
        "price": 165.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "90 minutes",
        "notes": ""
      },
      {
        "option_name": "Deep Tissue \u2014 60 minutes",
        "price": 135.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "60 minutes",
        "notes": ""
      },
      {
        "option_name": "Deep Tissue \u2014 90 minutes",
        "price": 170.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "90 minutes",
        "notes": ""
      },
      {
        "option_name": "Facial \u2014 60 minutes",
        "price": 120.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 30.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "60 minutes",
        "notes": "\u26a0 Yes massage price is per person"
      }
    ]
  },
  {
    "category": "Private Cuisine",
    "wix_form_name": "Private Chef",
    "service_name": "Private Chef Buffet (Dining Memories)",
    "company": "Dining Memories",
    "contact": "7401794",
    "booking_method": "",
    "info_needed": "Menu, # people, address",
    "internal_notes": "Chef arrives 1 hour before",
    "options": [
      {
        "option_name": "Breakfast",
        "price": 65.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 2,
        "max_people": 3,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "Chef arrives 1 hour before \u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Breakfast",
        "price": 50.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 4,
        "max_people": 8,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Breakfast",
        "price": 45.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 9,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Brunch",
        "price": 85.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 2,
        "max_people": 3,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Brunch",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 4,
        "max_people": 8,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Brunch",
        "price": 65.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 9,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "3-Course / Caribbean Menu",
        "price": 140.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": 2,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "Party agrees on 1 appetizer, main, dessert (6+ may pick 2) \u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "3-Course / Caribbean Menu",
        "price": 120.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 3,
        "max_people": 4,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "3-Course / Caribbean Menu",
        "price": 110.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 5,
        "max_people": 7,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "3-Course / Caribbean Menu",
        "price": 100.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 8,
        "max_people": 10,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "3-Course / Caribbean Menu",
        "price": 90.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 11,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Local Menu",
        "price": 80.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 8,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Grill / BBQ",
        "price": 100.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 8,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Taco Night",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 6,
        "max_people": null,
        "downpayment_percent": 10.0,
        "downpayment_fixed": 5.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 Say Menu is attached in responses to these emails"
      },
      {
        "option_name": "Add-on: Mimosas",
        "price": 15.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "\u26a0 ANSWER: $15 per person? And does your normal 10%+$5pp downpayment apply to add-ons?"
      },
      {
        "option_name": "Add-on: Kids Menu",
        "price": 25.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Old sheet says 'no on top on this' \u26a0 ANSWER: $25 per child? What does 'no on top on this' mean for your cut?"
      }
    ]
  },
  {
    "category": "Private Cuisine",
    "wix_form_name": "Private Chef",
    "service_name": "Private Cookout & Paella (Flo Chef)",
    "company": "Flo Chef",
    "contact": "6990175",
    "booking_method": "",
    "info_needed": "Menu, # people, address",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Paella",
        "price": 55.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 1,
        "max_people": 9,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 CONFIRM: do Paella/Cookout inquiries come in through the 'Private Chef' Wix form or a different form?"
      },
      {
        "option_name": "Paella",
        "price": 50.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 10,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Cookout \u2014 Menu Option 1",
        "price": 75.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 2,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": "\u26a0 ANSWER: minimum number of people for Cookout?"
      },
      {
        "option_name": "Cookout \u2014 Menu Option 2",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 2,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Cookout \u2014 Menu Option 3",
        "price": 70.0,
        "price_unit": "per_person",
        "child_price": 0,
        "min_people": 2,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 15.0,
        "downpayment_per_person": true,
        "timing": "",
        "notes": ""
      }
    ]
  },
  {
    "category": "Moments",
    "wix_form_name": "Floating Breakfast",
    "service_name": "Floating Breakfast",
    "company": "Eduardo's",
    "contact": "6999823",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Timing, Menu",
    "internal_notes": "",
    "options": [
      {
        "option_name": "Vegan Breakfast",
        "price": 210.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Beautifully styled breakfast floating on your private pool"
      },
      {
        "option_name": "Sweet Breakfast",
        "price": 210.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Big Breakfast",
        "price": 210.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Extra Breakfast",
        "price": 30.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 100.0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "\u26a0 This extra breakfast option is for when they mention they want extra."
      }
    ]
  },
  {
    "category": "Moments",
    "wix_form_name": "Balloon Decoration",
    "service_name": "Balloon Decoration",
    "company": "Express your feelings / Isa",
    "contact": "",
    "booking_method": "WhatsApp",
    "info_needed": "Date, address, color scheme",
    "internal_notes": "",
    "options": [
      {
        "option_name": "(personal quote)",
        "price": 0,
        "price_unit": "quote",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Birthdays, proposals, surprises \u26a0 They need to send inspo pics and then we can send a price."
      }
    ]
  },
  {
    "category": "Moments",
    "wix_form_name": "Flower Arrangements",
    "service_name": "Flower Arrangements",
    "company": "",
    "contact": "",
    "booking_method": "WhatsApp",
    "info_needed": "Date, Time, Address",
    "internal_notes": "Vendor company name not on file yet \u2014 ask & fill in.",
    "options": [
      {
        "option_name": "(personal quote)",
        "price": 0,
        "price_unit": "quote",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "\u26a0 They need to send inspo pics and then we can send a price."
      }
    ]
  },
  {
    "category": "Transportation",
    "wix_form_name": "Airport Transportation",
    "service_name": "Airport Transportation",
    "company": "EC Tours",
    "contact": "5693588",
    "booking_method": "WhatsApp",
    "info_needed": "Flight info, amount of people",
    "internal_notes": "",
    "options": [
      {
        "option_name": "One Way \u2014 1 to 5 people",
        "price": 60.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": 5,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "One Way \u2014 6 to 10 people",
        "price": 100.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 6,
        "max_people": 10,
        "downpayment_percent": 0,
        "downpayment_fixed": 20.0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Round Trip \u2014 1 to 5 people",
        "price": 100.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 1,
        "max_people": 5,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      },
      {
        "option_name": "Round Trip \u2014 6 to 10 people",
        "price": 160.0,
        "price_unit": "flat_total",
        "child_price": 0,
        "min_people": 6,
        "max_people": 10,
        "downpayment_percent": 0,
        "downpayment_fixed": 40.0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": ""
      }
    ]
  },
  {
    "category": "Transportation",
    "wix_form_name": "Car Rental",
    "service_name": "Car Rental",
    "company": "Turo Car rental",
    "contact": "7308338",
    "booking_method": "WhatsApp",
    "info_needed": "Flight info, Name, Car size, Phone",
    "internal_notes": "Airport pick-up included",
    "options": [
      {
        "option_name": "Sedan",
        "price": 50.0,
        "price_unit": "per_day",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Airport pick-up included; $300 deposit \u26a0 There is no downpayment collected here. Guest need to confirm if they are good with the price. Then we confirm the booking with vendor. Make the invoice based on the price of the service/car. They will pay this ammount when they car rental company picks them up. They need to answer some questions for the booking. I Need their Full name, Flight arrival info, email, phone number, picture of ID."
      },
      {
        "option_name": "Mid-size SUV",
        "price": 85.0,
        "price_unit": "per_day",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Airport pick-up included; $500 deposit \u26a0 There is no downpayment collected here. Guest need to confirm if they are good with the price. Then we confirm the booking with vendor. Make the invoice based on the price of the service/car. They will pay this ammount when they car rental company picks them up. They need to answer some questions for the booking. I Need their Full name, Flight arrival info, email, phone number, picture of ID."
      },
      {
        "option_name": "SUV",
        "price": 100.0,
        "price_unit": "per_day",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Airport pick-up included; $500 deposit \u26a0 There is no downpayment collected here. Guest need to confirm if they are good with the price. Then we confirm the booking with vendor. Make the invoice based on the price of the service/car. They will pay this ammount when they car rental company picks them up. They need to answer some questions for the booking. I Need their Full name, Flight arrival info, email, phone number, picture of ID."
      },
      {
        "option_name": "11-Seater Van",
        "price": 100.0,
        "price_unit": "per_day",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Airport pick-up included; $500 deposit \u26a0 There is no downpayment collected here. Guest need to confirm if they are good with the price. Then we confirm the booking with vendor. Make the invoice based on the price of the service/car. They will pay this ammount when they car rental company picks them up. They need to answer some questions for the booking. I Need their Full name, Flight arrival info, email, phone number, picture of ID."
      },
      {
        "option_name": "Jeep",
        "price": 250.0,
        "price_unit": "per_day",
        "child_price": 0,
        "min_people": null,
        "max_people": null,
        "downpayment_percent": 0,
        "downpayment_fixed": 0,
        "downpayment_per_person": false,
        "timing": "",
        "notes": "Airport pick-up included; $500 deposit \u26a0 There is no downpayment collected here. Guest need to confirm if they are good with the price. Then we confirm the booking with vendor. Make the invoice based on the price of the service/car. They will pay this ammount when they car rental company picks them up. They need to answer some questions for the booking. I Need their Full name, Flight arrival info, email, phone number, picture of ID."
      }
    ]
  }
];
